Networkteam:
  Neos:
    Vite:
      server:
        _default:
          url: http://localhost:5173/

        # You can provide a different URL (port) for the server per site per site package key:
        #
        ## MyExample.Site:
        ##   url: http://localhost:5174/

Neos:
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Vite: true
